# Generated by Django 5.2.5 on 2025-08-29 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
