name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        env:
          # AES_KEY_HEX should be set as a GitHub Repository Secret (Settings -> Secrets).
          # The workflow will fail if the secret is not provided to avoid using demo keys.
          AES_KEY_HEX: ${{ secrets.AES_KEY_HEX }}
        run: |
          if [ -z "$AES_KEY_HEX" ]; then echo "AES_KEY_HEX not set in secrets"; exit 1; fi
          python manage.py test --verbosity=2
